import babelify          from 'babelify';
import browserify        from 'browserify';
import gulp              from 'gulp';
import gulpCleanCss      from 'gulp-clean-css';
import gulpHtmlmin       from 'gulp-htmlmin';
import gulpImagemin      from 'gulp-imagemin';
import gulpJsonlint      from 'gulp-jsonlint';
import gulpJsonminify    from 'gulp-jsonminify';
import gulpPostcss       from 'gulp-postcss';
import gulpSourcemaps    from 'gulp-sourcemaps';
import gulpSvgmin        from 'gulp-svgmin';
import gulpSvgstore      from 'gulp-svgstore';
import gulpUglify        from 'gulp-uglify';
import gulpZip           from'gulp-zip' ;
import postcssCssnext    from 'postcss-cssnext';
import postcssImport     from 'postcss-import';
import stylelint         from 'stylelint';
import vinylBuffer       from 'vinyl-buffer';
import vinylSourceStream from 'vinyl-source-stream';

import pkg from './package.json';

const dirs = {
  source: './source',
  dest  : './dist'
};

gulp.task('css', () => {
  return gulp.src(`${dirs.source}/assets/css/style.css`)
    .pipe(gulpSourcemaps.init())
    .pipe(gulpPostcss([
      postcssImport(),
      postcssCssnext({
        features: {
          rem: false
        }
      })
    ]))
    .pipe(gulpCleanCss())
    .pipe(gulpSourcemaps.write('.'))
    .pipe(gulp.dest(`${dirs.dest}/assets`));
});

gulp.task('images:assets', () => {
  return gulp.src(`${dirs.source}/assets/images/**/*.{gif,ico,jpg,jpeg,png}`)
    .pipe(gulpImagemin())
    .pipe(gulp.dest(`${dirs.dest}/assets`));
});

gulp.task('js', () => {
  const b = browserify({
    entries: `${dirs.source}/assets/js/script.js`,
    transform: [babelify]
  });

  return b.bundle()
    .pipe(vinylSourceStream('script.js'))
    .pipe(vinylBuffer())
    .pipe(gulpSourcemaps.init())
    .pipe(gulpUglify())
    .pipe(gulpSourcemaps.write('.'))
    .pipe(gulp.dest(`${dirs.dest}/assets`));
});

gulp.task('json', () => {
  return gulp.src(`${dirs.source}/**/*.json`)
    .pipe(gulpJsonminify())
    .pipe(gulp.dest(`${dirs.dest}`));
});

gulp.task('lint:css', () => {
  return gulp.src(`${dirs.source}/assets/css/**/*.css`)
    .pipe(gulpPostcss([
      stylelint()
    ]));
});

gulp.task('lint:json', () => {
  return gulp.src(`${dirs.source}/data/**/*.json`)
    .pipe(gulpJsonlint())
    .pipe(gulpJsonlint.reporter());
});

gulp.task('liquid', () => {
  return gulp.src(`${dirs.source}/**/*.liquid`)
    .pipe(gulpHtmlmin({
      caseSensitive                : false,
      collapseBooleanAttributes    : true,
      collapseInlineTagWhitespace  : false,
      collapseWhitespace           : true,
      conservativeCollapse         : false,
      decodeEntities               : false,
      html5                        : true,
      includeAutoGeneratedTags     : false,
      keepClosingSlash             : false,
      minifyCSS                    : true,
      minifyJS                     : true,
      minifyURLs                   : true,
      preserveLineBreaks           : false,
      preventAttributesEscaping    : false,
      processConditionalComments   : false,
      processScripts               : false,
      quoteCharacter               : false,
      removeAttributeQuotes        : true,
      removeComments               : true,
      removeEmptyAttributes        : true,
      removeEmptyElements          : false,
      removeOptionalTags           : true,
      removeRedundantAttributes    : false,
      removeScriptTypeAttributes   : true,
      removeStyleLinkTypeAttributes: true,
      removeTagWhitespace          : true,
      sortAttributes               : true,
      sortClassName                : true,
      trimCustomFragments          : true,
      useShortDoctype              : true
    }))
    .pipe(gulp.dest(`${dirs.dest}`));
});

gulp.task('svg:icons', () => {
  return gulp.src(`${dirs.source}/assets/images/icons/**/*.svg`)
    .pipe(gulpSvgmin())
    .pipe(gulpSvgstore())
    .pipe(gulp.dest(`${dirs.dest}/assets`));
});

gulp.task('zip', ['build'], () => {
  return gulp.src('./dist/**/*')
    .pipe(gulpZip(`${pkg.name}.zip`))
    .pipe(gulp.dest('./'));
});

gulp.task('watch', () => {
  gulp.watch(`${dirs.source}/**/*.html`, ['html']);
  gulp.watch(`${dirs.source}/assets/css/**/*.css`, ['lint:css', 'css']);
  gulp.watch(`${dirs.source}/assets/js/**/*.js`, ['js']);
  gulp.watch(`${dirs.source}/assets/images/**/*.{gif,ico,jpg,jpeg,png}`, ['images:assets']);
  gulp.watch(`${dirs.source}/assets/images/icons/**/*.svg`, ['svg:icons']);
  gulp.watch(`${dirs.source}/**/*.json`, ['lint:json', 'json']);
  gulp.watch(`${dirs.source}/**/*.liquid`, ['liquid']);
});

gulp.task('default', [
  'lint',
  'liquid',
  'css',
  'js',
  'images:assets',
  'json',
  'svg:icons',
  'watch'
]);

gulp.task('lint', [
  'lint:css',
  'lint:json'
]);

gulp.task('build', [
  'lint',
  'liquid',
  'css',
  'js',
  'images:assets',
  'json',
  'svg:icons'
]);

gulp.task('publish', [
  'zip'
]);
